#!/bin/bash

set -e

pushd /db-init-scripts

psql -v ON_ERROR_STOP=1 -f faa.sql 
psql -v ON_ERROR_STOP=1 -f fwa.sql 
psql -v ON_ERROR_STOP=1 -f setup.sql 

pushd contact && psql -v ON_ERROR_STOP=1 -f run.sql && popd
pushd area && psql -v ON_ERROR_STOP=1 -f run.sql && popd
pushd alert && psql -v ON_ERROR_STOP=1 -f run.sql && popd
pushd notification && psql -v ON_ERROR_STOP=1 -f run.sql && popd

popd
